### ISSUE TITLE
Error message: error during import

### ISSUE THREAD

**Issue by andrazrepar** [elexis-eu/elexifier#27]
Display message about import errors and a link to an article about well-formed XMLs

**Comment by inl-ct** [comment]
Your dictionary file cannot be uploaded as the file is not well-formed. 
(+ if possible the first problematic line in the file, or some indication of why it is not well-formed)
Please check the user guide (ADD LINK) for more information on well-formed XML.

**Comment by gradisarjoze** [comment]
@andrazrepar please provide a link to info about well-formed xml.

**Comment by andrazrepar** [comment]
Let's use this one for now: https://elexifier.elex.is/help/

**Comment by gradisarjoze** [comment]
Message updated
