### ISSUE TITLE
Download error message

### ISSUE THREAD

**Issue by andrazrepar** [elexis-eu/elexifier#29]
Add an error message if download preparation fails. There is no message currently, only the Download button appears again.

**Comment by andrazrepar** [comment]
Current process:
- click Download
- select with or without namespaces
- wait for processing to finish
- download
- if file preparation fails, nothing happens, the process starts from the beginning

New process:
- click Download
- select with or without namespaces
- wait for processing to finish
- download
- if file preparation fails, display a message (i.e. file preparation failed) along with a Try again button which starts the process again

**Comment by LukeItUp** [comment]
New download status has been added to elexifier-api [develop](https://github.com/elexis-eu/elexifier-api/tree/develop) branch.
Status changes to **Error** when the xml download process fails and you can restart the process.

**Comment by gradisarjoze** [comment]
Deployed on staging.
