### ISSUE TITLE
Add admin panel for XMLs

### ISSUE THREAD

**Issue by andrazrepar** [elexis-eu/elexifier#30]
A new admin screen for xml files

**Comment by andrazrepar** [comment]
Similar to the PDF Admin panel, add information about errors occuring in three places:
- Upload and initial file processing
- Creating transformations
- File preparation and download

The list of errors should have information about error type (one of the 3 types above) and a reference to the dictionary and transformation (transformation only for the last two error types)

**Comment by LukeItUp** [comment]
New errors have been added to elexifier-api [develop](https://github.com/elexis-eu/elexifier-api/tree/develop) branch.

You can get them with the following http call and optional filter parameters:
_**GET /api/support/list?tag=TAG&dsid=DATASET_ID**_

The types are stored in error log tags:
- Uploading and initial file processing: **upload**
- Creating transformation: **xml_new**
- File preparation and download: **xml_download**
(older tags)
- ML fails: **ml_error**
- When ML finishes (error log contains the ML report): **ml_finished**

**Comment by andrazrepar** [comment]
I now see PDF errors under both sections (e.g. ml_error under XML)

**Comment by gradisarjoze** [comment]
Filter fixed.

**Comment by andrazrepar** [comment]
@LukeItUp, can we also add errors that occur on the transformation page
<img width="2212" alt="image" src="https://user-images.githubusercontent.com/36896866/164421016-e0348bdf-f0c5-4eaf-ba21-daa27ce9455d.png">

I think these are not included now?

**Comment by LukeItUp** [comment]
Added new error log when transformation fails to update.
