### ISSUE TITLE
PDF pos mapping

### ISSUE THREAD

**Issue by andrazrepar** [elexis-eu/elexifier#31]
Add an additional step for PDF transformation allowing the user to map POS tags in the document with UD tags.

**Comment by andrazrepar** [comment]
Similar to character mapping, but with predefined values, we map POS values with UD tags (we already have them in the XML workflow). After ML finishes, extract all unique values in the POS container and prepare a dropdown list to be displayed in the UI. 

The user selects a POS value from the dictionary from a dropdown list on the left hand side, and then selects a corresponding UD value from the dropdown list on the right hand side.

**Comment by LukeItUp** [comment]
Added two new api calls:
- GET /api/ml/DSID/pos_map?refresh=1
   - returns json with "pos_map" field
   - refresh is optional parameter and downloads pos elements from Lexonomy preview
- POST /api/ml/DSID/pos_map
   - accepts json with "pos_map" field containing new pos map

**Comment by andrazrepar** [comment]
We need to add another panel here below
<img width="226" alt="image" src="https://user-images.githubusercontent.com/36896866/160759960-60c4a66a-4b87-402d-8803-1ea3af8e0c7b.png">
Name: Map POS elements

**Comment by gradisarjoze** [comment]
This is now deployed to staging.
