### ISSUE TITLE
New metadata fields

### ISSUE THREAD

**Issue by andrazrepar** [elexis-eu/elexifier#33]
based on Clarin.si

**Comment by andrazrepar** [comment]
No changes in functionality, but new fields will need to be added and sent to the transformation script.

**Comment by gradisarjoze** [comment]
Where can the new fields be found? @andrazrepar

**Comment by andrazrepar** [comment]
https://www.clarin.si/repository/xmlui/page/metadata?locale-attribute=en

**Comment by andrazrepar** [comment]
Unless I am mistaken, metadata is just a json field in the database, so we can change it on the frontend without any backend modifications, right @LukeItUp ?

**Comment by LukeItUp** [comment]
Yes, metadata is just a json field.

**Comment by andrazrepar** [comment]
Let's wait with this one, the metadata will come from Clarin API.
