### ISSUE TITLE
Get dictionary form Clarin.si DOI

### ISSUE THREAD

**Issue by andrazrepar** [elexis-eu/elexifier#37]

**Comment by andrazrepar** [comment]
I think @LukeItUp has to prepare and endpoint.

**Comment by andrazrepar** [comment]
There is an API, we will get the documentation

**Comment by gradisarjoze** [comment]
This is now deployed to staging.

<img width="906" alt="Screenshot 2022-03-28 at 20 28 27" src="https://user-images.githubusercontent.com/25753066/160463170-ebf84632-fbd5-40bc-b82d-f798ba8a1d0e.png">
<img width="709" alt="Screenshot 2022-03-28 at 20 28 51" src="https://user-images.githubusercontent.com/25753066/160463169-6a549e26-87d3-48cf-971d-7d78492e76cf.png">
<img width="727" alt="Screenshot 2022-03-28 at 20 28 56" src="https://user-images.githubusercontent.com/25753066/160463164-5dc51e29-f66f-42dd-ac23-872eaf7d3fc4.png">

**Comment by andrazrepar** [comment]
I tested this and it works, we need to add two things:
- when pulling files, we need to define the acronym, because it doesn't come from the metadata.
- we need a check to tell the user if they entered a badly formatted DOI link. I tried with https://www.clarin.si/repository/xmlui/bitstream/handle/11356/1475 nothing happened. We need a message saying that the link is not correct.

**Comment by andrazrepar** [comment]
@LukeItUp I see that you now have a hardcoded attribute CLRN. Can you update the endpoint to accept a parameter from the frontend. It should go like this:
- Enter DOI and click Load dictionary
- Select files and define the acronym
- Click Pull files

**Comment by LukeItUp** [comment]
The API endpoint now accepts acronym field. If field is missing, default value is `CLRN`.
```
POST /api/clarin/new
BODY: {"handle": "http://hdl.handle.net/11356/1475", "files": ["Mreznik(a-f).xml"], "acronym": "ACRO" }
```

**Comment by gradisarjoze** [comment]
Acronym field added.

**Comment by andrazrepar** [comment]
One more thing, can we add a "Select all" checkbox when displaying the files? Especially with zip files, there could be hundreds of files and we need to have the option to quickly select all of them.

**Comment by gradisarjoze** [comment]
Added "Toggle all" button.
