### ISSUE TITLE
position of cit end tag wrong

### ISSUE THREAD

**Issue by inl-ct** [elexis-eu/elexifier#38]
The end <cit> of an example should be after the translations of the example.

TEI Lex-0 and TEI  example:

    <cit type="example">
        <quote>elle était horrifiée par la dépense</quote>
        <cit type="translation" xml:lang="en">
           <quote>she was horrified at the expense</quote>
        </cit>
     </cit>

Output Elexifier:
<seg m:e="SenseExample">
     <cit type="example">
       <quote m:e="text">"einnota bleiur"</quote>
     </cit>
     <seg m:e="Equivalent" a:text="&quot;einnota bleiur&quot;"/>
     <cit type="translation">
       <quote>"einnota bleiur"</quote>
     </cit>
     <seg m:e="Equivalent" a:language="da" a:text="engangsbleer"/>
     <cit type="translation">
       <quote>engangsbleer</quote>
     </cit>

**Comment by andrazrepar** [comment]
This was resolved by additon the adopt selector option in the example transformer
