### ISSUE TITLE
Remove New Dictionary button

### ISSUE THREAD

**Issue by andrazrepar** [elexis-eu/elexifier#43]
Let's remove the New Dictionary button at the bottom of the files list and use only the two options on the main pane (Upload a dictionary, Pull from Clarin)

![image](https://user-images.githubusercontent.com/36896866/164396393-096b1c15-f672-4ec5-b3d7-18f041362c4d.jpeg)

**Comment by gradisarjoze** [comment]
Deployed to staging.
