### ISSUE TITLE
Changes to the Example transformer

### ISSUE THREAD

**Issue by andrazrepar** [elexis-eu/elexifier#48]
The Example transformer has a new JSON specification:

```"ex": {
        "type": "simple",
        "selector": {
            "type": "xpath",
            "expr": ".//Example"
        },
        "attr": "{http://elex.is/wp1/teiLex0Mapper/meta}innerText",
        "rex": "",
        "adoptSelector": {
            "type": "xpath",
            "expr": "..//Translation"
        }
    }
```

There is a new element called `adoptSelector`, which tells the script to move the example translation into the Example element. You can find an example of how it works at http://capybara.ijs.si/janez/elexis/transformDemo.html in the MLDS dictionary.

This means that the UI for the Example transformer needs an additional field where users can enter the xpath of the translation element.
<img width="381" alt="image" src="https://user-images.githubusercontent.com/36896866/165720670-3890727c-f34f-432a-ac3a-ed08141c110e.png">
Let's add it under VALUE. It needs to offer the same prefill options as the main element field when you start typing.

**Comment by LukeItUp** [comment]
Staging has the latest version of transformation script.

**Comment by gradisarjoze** [comment]
Deployed to staging
