### ISSUE TITLE
No headwords visible in https://app.elexifier.elex.is/dictionaries/xml/595/transformations/474

### ISSUE THREAD

**Issue by andrazrepar** [elexis-eu/elexifier#51]
It seems that the headword entities for this dictionary are not correct in the database:
`{
  "dsid": 595,
  "hw": "\n",
  "id": 5599044,
  "is_short_name": false,
  "name": "<Entry hw="
}`

`\n` character instead of the actual value. @LukeItUp, can you check what is going on?

**Comment by LukeItUp** [comment]
There was an error due to a new version of transformation script. It's fixed now.
