### ISSUE TITLE
Strip namespaces checkbox stopped working in the latest version

### ISSUE THREAD

**Issue by andrazrepar** [elexis-eu/elexifier#58]
![image](https://user-images.githubusercontent.com/36896866/169995738-7144e616-864a-46b2-b32a-d56d0a208284.png)
Nothing happens when I check the box, but the query parameters are ok:

![image](https://user-images.githubusercontent.com/36896866/169995859-a424de34-cfa0-479c-8b31-97c9f4de9542.png)

**Comment by LukeItUp** [comment]
This is fixed now.
